theme: jekyll-theme-architect
title: Z616 Comic Books and Their Readers, Spring 2026
description: Qualitative, quantitative, and digital methods for studying comic readers and fans
markdown: kramdown
